site_name: Sibila
site_url: https://jndiogo.github.io/sibila/
repo_url: https://github.com/jndiogo/sibila

nav:
  - Start:
    - index.md
    - what.md
  
    - Getting Started:
      - installing.md
      - first_run.md

    - Creating Models:
      - models/remote_model.md
      
      - Local model:
        - models/local_model.md
        - models/find_local_models.md
        - models/setup_format.md

      - Models factory:
        - models/models_factory.md
        - models/models_json.md
        - models/formats_json.md

    - Extracting Structured Data:
      - extract/simple_types.md
      - extract/enums.md
      - extract/dataclass.md
      - extract/pydantic.md
      - extract/free_text.md

    - tools.md

    - tips.md

  - Examples:
    - examples/index.md
    - examples/hello_model.md
    - examples/from_text_to_object.md
    - "Extract Pydantic": examples/extract.md
    - examples/extract_dataclass.md
    - examples/tag.md
    - examples/quick_meeting.md
    - examples/tough_meeting.md
    - examples/compare.md
    - examples/interact.md

  - API Reference:
    - api-reference/model.md
    - api-reference/models.md
    - api-reference/generation.md
    - api-reference/thread.md
    - api-reference/multigen.md
    - api-reference/tools.md
    - api-reference/tokenizer.md




theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes

    - toc.follow

    - content.code.copy
    # - content.code.select

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  


extra_css:
  - stylesheets/extra.css

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          paths: [sibila]
          options:
            # general: https://mkdocstrings.github.io/python/usage/configuration/general/
            show_bases: false
            show_source: true
            preload_modules:
              - typing

            # headings: https://mkdocstrings.github.io/python/usage/
            heading_level: 3
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_root_members_full_path: false

            # members: https://mkdocstrings.github.io/python/usage/configuration/members/
            inherited_members: true            
            members_order: source
            group_by_category: false

            # docstrings: https://mkdocstrings.github.io/python/usage/configuration/docstrings/
            docstring_style: "google"
            docstring_section_style: table
            merge_init_into_class: true
            show_docstring_attributes: false
            show_if_no_docstring: true

            # signature: https://mkdocstrings.github.io/python/usage/configuration/signatures/
            line_length: 60
            separate_signature: True
            show_signature: true
            show_signature_annotations: false
            signature_crossrefs: true

          import:
            - https://docs.python.org/3/objects.inv
            
  #- mkdocs-jupyter:



markdown_extensions:
  - attr_list
  - md_in_html
  - tables

  - admonition
  - pymdownx.details

  - toc:
      permalink: "#"
      title: Contents

  - pymdownx.snippets:
      check_paths: true
      base_path: ["examples"]

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


watch:
  - sibila
  - docs
  - examples
